language: go
sudo: false
go:
  - 1.9.x
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file:
    - "bin/sshs-${TRAVIS_TAG}-linux-amd64"
    - "bin/sshs-${TRAVIS_TAG}-darwin-amd64"
  skip_cleanup: true
  on:
    tags: true
install:
  - go get -d -t -v ./...
  # - go get -v golang.org/x/crypto/ssh
  # - go get -v golang.org/x/crypto/ssh/terminal
  # - go get -v gopkg.in/yaml.v2
  # - go get -v gopkg.in/urfave/cli.v1
  # - go get -v github.com/rodaine/table
  # - go get -v github.com/fatih/color
script:
  - chmod +x build.sh
  - ./build.sh
  # - GOARCH=amd64 GOOS=linux go build -o bin/sshs-linux-amd64 ./
notifications:
  email:
    on_failure: always
    on_success: never